Update to C++11 idiom for prohibiting copying of classes
When copying of the classes was first prohibited [1] it had to use the
original technique of a private declaration and no definition because
GParted was still being compiled with pre-C++11 compilers at the time.
Now GParted requires C++14 compilation [2] update to the C++11 syntax of
declaring the functions as deleted [3][4][5].

Compiling code containing these lines:
    OperationCheck o1(dev, ptn);  // Parameterised construction allowed
    OperationCheck o2 = o1;       // Copy construction generates an error
    o2 = o1;                      // Copy assignment generates an error

Produces these errors:
    test.cc: In function 'void GParted::test()':
    test.cc:13:22: error: use of deleted function 'GParted::OperationCheck::OperationCheck(const GParted::OperationCheck&)'
      OperationCheck o2 = o1;       // Copy construction generates an error
                          ^~
    In file included from test.cc:3:
    ../include/OperationCheck.h:33:2: note: declared here
      OperationCheck(const OperationCheck& src) = delete;             // Copy construction prohibited
      ^~~~~~~~~~~~~~
    test.cc:14:7: error: use of deleted function 'GParted::OperationCheck& GParted::OperationCheck::operator=(const GParted::OperationCheck&)'
      o2 = o1;                      // Copy assignment generates an error
           ^~
    In file included from test.cc:3:
    ../include/OperationCheck.h:34:18: note: declared here
      OperationCheck& operator=(const OperationCheck& rhs) = delete;  // Copy assignment prohibited
                      ^~~~~~~~

[1] commit b516b1093c6ac0e65b87e125204d49a7a7fdf0d3
    Use pointers to Partitions in Operation classes (#759726)

[2] commit 7218d0884e834124b8093ee187968297e4c8328f
    Require C++14 compilation (!137)

[3] C++11 - the new ISO C++ standard, control of defaults: default and
    delete
    https://www.stroustrup.com/C++11FAQ.html#default
        The common idiom of "prohibiting copying" can now be expressed
        directly:
            class X {
            public:
                    // ...
                    X& operator=(const X&) = delete;  // Disallow copying
                    X(const X&) = delete;
            };

[4] C++11 Language Extensions = Classes, =default and =delete
    https://isocpp.org/wiki/faq/cpp11-language-classes#default-delete
        [[Identical text as Bjarne Stroustrup's C++11 FAQ]]

[5] What Is A Deleted Function In Modern C++?
    https://learncplusplus.org/what-is-a-deleted-function-in-modern-c/
        A deleted function is a function that contains =delete; in its
        prototype.  This construction, introduced with C++11, indicates
        that the function may not be used.  This construction can be
        used to forbid the usage of default language facilities (like
        default constructors or default operators) or problematic
        conversions.