Increase required gtkmm-2.4 version 2.16.0 for gtk_show_uri (#608065)
Building GParted with gtkmm-2.4 version 2.14.0 would fail with:
     error: ‘gtk_show_uri’ was not declared in this scope.
This problem does not occur with version 2.16.0.