Detect busy status of ZFS member disks (!163)
So far GParted only recognises ZFS file systems and displays the ZFS
pool name as the label, by virtue of blkid.  That multiple issues were
reported both times blkid misdetected whole disk ZFS [1] indicates
notable GParted usage on machines with ZFS file systems.  3 reports the
first time and 2 reports the second time.  So lets improve ZFS support.

The aim of this patchset is to add as much support as possible with
minimal code changes and without running any ZFS specific commands.
Supportable features turn out to be:
* Busy detection
* Reporting mounted only mount points

Correct busy detection of a partition is crucial for GParted as it must
prevent Delete, Copy from, Paste into, Move and Format of a partition
while it is mounted or otherwise active to avoid data corruption.

This commit implements busy detection of ZFS member disks.

Create a ZFS pool.  This includes automatically creating the root
dataset and mounting it:
    # zpool create testpool /dev/sdb1
    # zpool status -P
      pool: testpool
     state: ONLINE
    config:

            NAME         STATE     READ WRITE CKSUM
            testpool     ONLINE       0     0     0
              /dev/sdb1  ONLINE       0     0     0

    errors: No known data errors

    # zfs list
    NAME       USED  AVAIL  REFER  MOUNTPOINT
    testpool   123K   832M    24K  /testpool

    # grep zfs /proc/mounts
    testpool /testpool zfs rw,seclabel,relatime,xattr,noacl,casesensitive 0 0

Use getting exclusive access to the ZFS member disk as a test of whether
it is inactive or busy.  This is the same technique previously used for
JBDs [2].  In this case exclusive access failed so this ZFS member disk
is busy:
    # python
    >>> import os
    >>> fd = os.open('/dev/sdb1', os.O_RDONLY|os.O_EXCL)
    Traceback (most recent call last):
      File "<python-input-1>", line 1, in <module>
        fd = os.open('/dev/sdb1', os.O_RDONLY|os.O_EXCL)
    OSError: [Errno 16] Device or resource busy: '/dev/sdb1'

Now export the ZFS pool, which includes unmounting all datasets:
    # zpool export testpool
    # zpool status
    no pools available

    # grep zfs /proc/mounts
    # grep zfs /proc/mounts | wc -l
    0

This time exclusive access succeeded so the ZFS member disk was
inactive:
   >>> fd = os.open('/dev/sdb1', os.O_RDONLY|os.O_EXCL)
   >>> print(fd)
   6
   >>> os.close(6)

[1] commit 4755f15de791f33fbe88fe65d351916230779370
    Implement blkid false detection of whole disk ZFS workaround (#310)

[2] commit 1950a7a09d53fdedbf70e1b0a854302a9c4ca832
    Report busy status of jbds (#89)

Closes !163 - Add minimal ZFS support - busy detection and mount point
              reporting