Fix Google Test compilation against GCC 15 libstdc++ (#281)
On Fedora 42 building Google Test library as part of unit testing fails
like this:
    $ make check
    ...
    make[3]: Entering directory '/home/fedora/programming/c/gparted/lib/gtest'
    ...
    libtool: compile:  g++ -std=gnu++11 ... -c src/gtest_main.cc ...
    In file included from src/gtest-all.cc:42:
    ./src/gtest-death-test.cc: In function 'pid_t testing::internal::ExecDeathTestSpawnChild(char* const*, int)':
    ./src/gtest-death-test.cc:1385:26: error: 'uintptr_t' does not name a type
     1385 |         reinterpret_cast<uintptr_t>(stack_top) % kMaxStackAlignment == 0);
          |                          ^~~~~~~~~
    ./src/gtest-death-test.cc:308:38: note: in definition of macro 'GTEST_DEATH_TEST_CHECK_'
      308 |     if (!::testing::internal::IsTrue(expression)) { \
          |                                      ^~~~~~~~~~
    ./src/gtest-death-test.cc:49:1: note: 'uintptr_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
       48 | # include <limits.h>
      +++ |+#include <cstdint>
       49 |
    make[3]: *** [Makefile:504: src/gtest-all.lo] Error 1

It turns out that gtest-all.cc, which includes gtest-death-test.cc,
received the definition of uintptr_t via this chain of includes in
Fedora 41, with GCC 14 libstdc++:
    .../gparted/lib/gtest/src/gtest-all.cc
       38 | #include "gtest/gtest.h"
    .../gparted/lib/gtest/include/gtest/gtest.h
       57 | #include <memory>
    /usr/include/c++/14/memory
       76 | #  include <bits/align.h>
    /usr/include/c++/14/bits/align.h
       34 | #include <stdint.h>     // uintptr_t
    /usr/lib/gcc/x85_64-redhat-linux/14/include/stdint.h
        9 | #  include_next <stdint.h>
    /usr/include/stdint.h
       79 | typedef unsigned long int       uintptr_t;
(Tracked down using g++ -E, stop after the preprocessing stage).

However Fedora 42 updated to GCC 15 which included this change to
libstdc++ [1], which removed #include <stdint.h> from <bits/align.h>,
hence the above compilation failure.  As discussed in these recent
GParted commits [2][3] it is bad practice to depend on headers being
included transitively [4] for exactly this reason.  Fix by directly
including stdint.h in gtest-death-test.cc.

[1] libstdc++: Remove unnecessary use of <stdint.h>
    https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=3a817a4a5a6d94da9127af3be9f84a74e3076ee2
    https://github.com/gcc-mirror/gcc/commit/3a817a4a5a6d94da9127af3be9f84a74e3076ee2
[2] 9546bf1c93f7850856b8767872129c80f37f4ce8
    Add sigc++ #includes to many files
[3] a488502814a6cbcd44ac6fe1f374148ff7c73113
    Fix #includes for the FileSystem module
[4] Is it good practice to rely on headers being included transitively?
    https://softwareengineering.stackexchange.com/questions/262019/is-it-good-practice-to-rely-on-headers-being-included-transitively

Closes #281 - make check fails to build Google Test library on Fedora 42
              because uintptr_t is undefined