Stick with docker image ubuntu:24.04 in CI jobs (!165)
The Ubuntu CI jobs have just started failing like this:
    $ apt install -y build-essential gnome-common yelp-tools libglib2.0-dev-bin uuid-dev libparted-dev libgtkmm-3.0-dev policykit-1 libpolkit-gobject-1-dev
    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    Reading package lists...
    Building dependency tree...
    Reading state information...
    Package policykit-1 is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
    However the following packages replace it:
      polkitd  pkexec
    Error: Package 'policykit-1' has no installation candidate
    Uploading artifacts for failed job 00:03
    ...
    ERROR: Job failed: exit code 1

This is because now, shortly after the release of Ubuntu 26.04 LTS, the
docker image tag "latest" has moved from the 24.04 image to the 26.04
image [1] and in Ubuntu 26.04 the policykit-1 package doesn't exist.  It
has been replaced as described in the above error message.

Additionally Ubuntu 26.04 LTS has dropped the reiser4progs and
reiserfsprogs packages.  Neither of the other two distributions of
Alpine Linux and Rocky Linux used in CI jobs support reiser4 or
reiserfs.

So for now to resolve this CI job breakage and to continue to have
GParted's interfaces to the reiser4 and reiserfs file systems tested by
the CI jobs, stick with Ubuntu 24.04 LTS.

[1] Ubuntu Docker Official Image
    https://hub.docker.com/_/ubuntu/
        Supported tags and respective Dockerfile links
        ...
        * 24.04, noble-20260410, noble
        ...
        * 26.04, resolute-20260421, resolute, latest, rolling

Closes !165 - Fix ubuntu CI jobs failing after docker tag "latest"
              switched to 26.04