Stop copying one OperationDetail object over another in ntfs::resize() (#320)
Perform an ntfs resize operation and save the details to a file.  The
saved details are wrong and incomplete and don't match what was
performed or displayed in the UI.

The correct details shown in the UI:
    * Grow /dev/sdb1 from 64.00 MiB to 65.00 MiB               (SUCCESS)
      * calibrate /dev/sdb1                                    (SUCCESS)
      * check file system on /dev/sdb1 for errors and (if p... (SUCCESS)
      * grow partition from 64.00 to 65.00 MiB                 (SUCCESS)
      * grow file system to fill the partition                 (SUCCESS)
        * run simulation                                       (SUCCESS)
          * ntfsresize --force --force --no-action '/dev/sdb1' (SUCCESS)
              ...
              The read-only test run ended successfully.
        * real resize                                          (SUCCESS)
          * ntfsresize --force --force '/dev/sdb1'             (SUCCESS)
              ...
              Successfully resized NTFS on device '/dev/sdb1'.

The wrong details saved to file:
    ...
    * Grow /dev/sdb1 from 64.00 MiB to 65.00 MiB               (SUCCESS)
      * calibrate /dev/sdb1                                    (SUCCESS)
      * check file system on /dev/sdb1 for errors and (if p... (SUCCESS)
      * grow partition from 64.00 to 65.00 MiB                 (SUCCESS)
      * grow file system to fill the partition                 (SUCCESS)
>>      * real resize                                          (SUCCESS)
>>        * ntfsresize --force --force '/dev/sdb1'             (SUCCESS)
              ...
>>            Successfully resized NTFS on device '/dev/sdb1'.
>>      * real resize                                        (EXECUTING)

In the saved file the run simulation and it's sub-details were replaced
with the real resize.  The second real resize had no details and was
left in the executing state.

This was because of this code in ntfs::resize():
    210 //simulation...
    211 operationdetail.add_child(OperationDetail(_("run simulation")));
    212 OperationDetail& child_od = operationdetail.get_last_child();
    213 success = ! child_od.execute_command(cmd + " --no-action " ...);
    ...
    219 // Real resize
    220 operationdetail.add_child(OperationDetail(_("real resize")));
    221 child_od = operationdetail.get_last_child();
    222 success = ! child_od.execute_command(cmd + " " ...);
    ...

Line 211 to 220 worked as expected.  "run simulation" OperationDetail
created, ntfsresize --no-action command ran and output recorded to
sub-details.  "real resize" OperationDetail created.

Line 221 was assuming that the child_od reference can be made to refer
to a new object.  It can't [1].  Instead line 221 copied the "real
resize" OperationDetail over the top of the "run simulation"
OperationDetail.  Then line 222 ran the real ntfsresize and captured
the output into the first child OperationDetail.  The second "real
resize" OperationDetail created at line 220 was left empty in the
executing state.  Hence the details save to file.

Everything is displayed correctly in the UI because the Gtk::TreeStore
in the Dialog_Progress class takes copies of each OperationDetail
description into it's own hierarchy as it is produced.

As confirmation, temporarily delete the compiler generated copy
assignment operator by adding this into OperationDetail.h:
    OperationDetail& operator=(const OperationDetail& other) = delete;
and compile GParted.  It fails like this:
    $ make
    ...
    ntfs.cc: In member function 'virtual bool GParted::ntfs::resize(const GParted::Partition&, GParted::OperationDetail&, bool)':
    ntfs.cc:221:44: error: use of deleted function 'GParted::OperationDetail& GParted::OperationDetail::operator=(const GParted::OperationDetail&)'
      child_od = operationdetail.get_last_child();
                                                ^
    In file included from ../include/FileSystem.h:22,
                     from ../include/ntfs.h:23,
                     from ntfs.cc:19:
    ../include/OperationDetail.h:93:19: note: declared here
      OperationDetail& operator=(const OperationDetail& other) = delete;
                       ^~~~~~~~
There aren't any other occurrences of assigning over the top of an
OperationDetail because the reset of the code compiles with the
assignment operator deleted.

This was broken by commit [3].  Fix by creating a separate reference to
the "real resize" child OperationDetail.

[1] C++ FAQ: How can you reseat a reference to make it refer to a
    different object?
    https://isocpp.org/wiki/faq/references#reseating-refs
        No way.

        You can't separate the reference from the referent.

        Unlike a pointer, once a reference is bound to an object,  it
        can not be "reseated" to another object.  The reference isn't a
        separate object.  It has no identity.

[2] C++ FAQ: What happens if you assign to a reference?
    https://isocpp.org/wiki/faq/references#assigning-refs
        You change the state of the referent (the referent is the object
        to which the reference refers).

        Remember: the reference is the referent, so changing the
        reference changes the state of the referent.  In compiler writer
        lingo, a reference is an "lvalue" (something that can appear on
        the left hand side of an assignment operator).

[3] commit bef952471eff460355bdcfeccdabdf452c8dd462
    Transition all FileSystem::execute_command() calls to
    OperationDetail replacements (!132)

Closes #320 - Saved details of ntfs resize operation are wrong and
              incomplete