SQUASH: Update needed CI packages with yelp-tools (!24)
CI job ubuntu_build is failing like this:
    $ ./autogen.sh
    /usr/bin/gnome-autogen.sh
    ERROR: Tools to build the documentation were not found
    ERROR: yelp-tools package needs to be installed
    ERROR: Job failed: exit code 1
because the yelp-tools package is missing from the Ubuntu image:

Replace package rarian-compat with yelp-tools.

[FIXME: This commit should probably be squashed with "Convert to new
GNOME 3 yelp-tools documentation infrastructure (!24)" to avoid CI
failures.]

Closes !24 - Port to GNOME 3 yelp-tools documentation infrastructure