Fix translation of DocBook markup tag of the GParted Manual (!98)
As found by the GitLab Continuous Integration job on CentOS 7 with
itstool 2.0.2, building the GParted Manual breaks on the Russian
translation like this:
    $ ./autogen.sh
    $ make clean
    $ cd help
    $ make
    ...
    if ! test -d "ru/"; then mkdir "ru/"; fi
    if test -d "C"; then d="../"; else d="/home/mike/programming/c/gparted/help/"; fi; \
    mo="ru/ru.mo"; \
    if test -f "${mo}"; then mo="../${mo}"; else mo="/home/mike/programming/c/gparted/help/${mo}"; fi; \
    (cd "ru/" && itstool -m "${mo}" ${d}/C/index.docbook) && \
    touch "ru/ru.stamp"
    Error: Could not merge translations:
    'NoneType' object has no attribute 'node'
    make: *** [ru/ru.stamp] Error 1

On Fedora 35 with itstool 2.0.6 building the GParted Manual merely
reports a warning, leaving one paragraph untranslated, but the build
completes successfully:
    $ ./autogen.sh
    $ make clean
    $ cd help
    $ make
    ...
    if ! test -d "ru/"; then mkdir "ru/"; fi
    if test -d "C"; then d="../"; else d="/home/fedora/programming/c/gparted/help/"; fi; \
    mo="ru/ru.mo"; \
    if test -f "${mo}"; then mo="../${mo}"; else mo="/home/fedora/programming/c/gparted/help/${mo}"; fi; \
    (cd "ru/" && itstool -m "${mo}" ${d}/C/index.docbook) && \
    touch "ru/ru.stamp"
    Warning: Could not merge translation for msgid:
    Set the <application>grub</application> root device by specifying the device returned by the <command>find</command> command. This should be the partition containing the boot directory. <_:screen-1/>
    ...
    $ echo $?
    0

Fix translation of DocBook markup tag in the Russian translation of the
GParted Manual by commit:
    17f4c3176d3be29d2867c080c0b292643d470627
    Update Russian translation

Closes !98 - Fix translation of DocBook markup tag of the GParted Manual