Stop parallelising make distcheck in GitLab CI test jobs (!6)
Unfortunately parallelising 'make distcheck' causes it to fail like
this:

    $ nproc=`grep -c '^processor' /proc/cpuinfo` || nproc=1
    $ echo nproc=$nproc
    nproc=8
    ...
    $ make -j $nproc distcheck
    ...
    make[1]: Entering directory '/builds/mfleetwo/gparted/gparted-0.31.0-git/_build/sub'
    ERROR: files left after uninstall:
    ./share/icons/hicolor/icon-theme.cache
    Makefile:896: recipe for target 'distuninstallcheck' failed
    make[1]: Leaving directory '/builds/mfleetwo/gparted/gparted-0.31.0-git/_build/sub'
    make[1]: *** [distuninstallcheck] Error 1
    make: *** [distcheck] Error 1
    Makefile:840: recipe for target 'distcheck' failed
    ERROR: Job failed: exit code 1

Therefore go back to serial 'make distcheck'.

Closes !6 - Reduce the time taken by the GitLab CI jobs