Fix corrupted FS copy into or out of encrypted Logical Volume (#328)
GParted block copy corrupts a file system when copying it either into
or out of an encrypted Logical Volume.

Block device setup:
* 512 MiB Logical Volume /dev/testvg/lvol1
* LUKS encryption created in the Logical Volume
  (LUKS2 reserves 16 MiB at the start so the size of the encrypted data
  is 496 MiB).
* Open LUKS encryption mapping /dev/mapper/lvol1_crypt
* 496 MiB partition /dev/sdb2

    # lsblk -o name,maj:min,size,type,fstype,label,mountpoint /dev/sdb
    NAME              MAJ:MIN  SIZE TYPE  FSTYPE      LABEL     MOUNTPOINT
    sdb                 8:16     8G disk
    +-sdb1              8:17     1G part  LVM2_member
    | +-testvg-lvol1  252:0    512M lvm   crypto_LUKS
    |   +-lvol1_crypt 252:1    496M crypt
    +-sdb2              8:18   496M part

Test 1: Copy a filled btrfs file system from the encrypted Logical
Volume /dev/mapper/lvol1_crypt to the partition /dev/sdb2.  Using btrfs
because it checksums all data and metadata which will be used to detect
corruption.

Create the btrfs file system.
    # mkfs.btrfs -L copy_test /dev/mapper/lvol1_crypt

Fill the file system.  Create lots of files with unique (random) data
thus each protected by unique checksums.  Don't use zero filled files
because there would be a good chance that a mis-copied sector would
replace one zero filled sector with another, thus providing no
detectable corruption.
    # mount /dev/mapper/lvol1_crypt /mnt/1
    # cd /mnt/1
    # for i in `seq --equal-width 0 399`
    > do
    >     dd if=/dev/urandom bs=1M count=1 of=/mnt/0/file-$i.bin status=none
    > done
    # btrfs filesystem sync /mnt/1
    # df -h /mnt/1
    Filesystem               Size  Used Avail Use% Mounted on
    /dev/mapper/lvol1_crypt  496M  408M   15M  97% /mnt/1
    # cd ~
    # umount /mnt/1

Use GParted to copy the btrfs file system from the encrypted Logical
Volume to a partition.  The copy reports success!
    * Copy /dev/testvg/lvol1 to /dev/sdb2                      (SUCCESS)
      * calibrate /dev/testvg/lvol1                            (SUCCESS)
          path: /dev/testvg/lvol1 (logical volume)
          size: 128 (512.00 MiB)
          encrypted path: /dev/mapper/lvol1_crypt
      * calibrate /dev/sdb2                                    (SUCCESS)
          path: /dev/sdb2 (partition)
          start: 2099200
          end: 3115007
          size: 1015808 (496.00 MiB)
      * clear old file system signatures in /dev/sdb2          (SUCCESS)
      * set partition type on /dev/sdb2                        (SUCCESS)
      * copy file system from /dev/mapper/lvol1_crypt to /de...(SUCCESS)
          using internal algorithm
          copy 496.00 MiB
        * finding optimal block size
        * copy 416.00 MiB using a block size of 8.00 MiB       (SUCCESS)
          496.00 MiB (520093696 B) copied
      * check file system on /dev/sdb2 for errors and (if po...(SUCCESS)
        * btrfs check '/dev/sdb2'                              (SUCCESS)

Btrfs check didn't report any errors!  Scrub the btrfs file system to
verify all data and metadata against their checksums.
    # btrfs scrub start -B /dev/sdb2
    ERROR: '/dev/sdb2' is not a mounted btrfs device
    # mount /dev/sdb2 /mnt/2
    # btrfs scrub start -B /dev/sdb2
    Starting scrub on devid 1
    scrub done for 61e933f4-c4a2-40ca-b7e1-a26955df93ab
    Scrub started:    Wed Sep 16 08:47:14 2026
    Status:           finished
    Duration:         0:00:03
    Total to scrub:   401.84MiB
    Rate:             133.95MiB/s
    Error summary:    csum=17664
      Corrected:      0
      Uncorrectable:  17664
      Unverified:     0
    ERROR: there are 1 uncorrectable errors

17664 checksum errors reported.  Uncorrectable because this is a single
device btrfs with only one copy of the data, which has been corrupted.
The kernel syslog is filled with btrfs errors.  A small fragment:
    # dmseg | grep BTRFS
    ...
    [ 6786.409900] BTRFS info (device sdb2): scrub: started on devid 1
    [ 6787.466946] BTRFS error (device sdb2): scrub: unable to fixup (regular) error at logical 394461184 on dev /dev/sdb2 physical 436404224
    [ 6787.467055] BTRFS warning (device sdb2): scrub: checksum error at logical 394461184 on dev /dev/sdb2, physical 436404224 root 5 inode 580 offset 196608 length 4096 links 1 (path: file-323.bin)
    ...

On the source btrfs all the files can be accessed:
    # mount /dev/testvg/lvol1_crypt /mnt/1
    # cat /mnt/1/* > /dev/null

But on the destination btrfs some files are corrupted and can't be
accessed:
    # cat /mnt/2/* > /dev/null
    cat: /mnt/2/file-323.bin: Input/output error
    cat: /mnt/2/file-324.bin: Input/output error
    cat: /mnt/2/file-325.bin: Input/output error
    ...

Cleanup the btrfs file systems:
    # cd ~
    # umount /mnt/1
    # pv -B 1M /dev/zero > /dev/mapper/lvol1_crypt
    # umount /mnt/2
    # pv -B 1M /dev/zero > /dev/sdb2

Test 2: Copy verifyable data pattern from the partition /dev/sdb2 to the
encrypted Logical Volume /dev/mapper/lvol1_crypt.

Fill partition with verifyable data pattern [1].
    # write-sector-pattern.py /dev/sdb2
    INFO: Sector size 512
    INFO: Wrote 1815808 sectors

    # hexdump -C /dev/sdb2 | fgrep -v '*' | head -10
    00000000  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 30 0a  |SECTOR=00000000.|
    00000200  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 31 0a  |SECTOR=00000001.|
    00000400  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 32 0a  |SECTOR=00000002.|
    00000600  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 33 0a  |SECTOR=00000003.|
    00000800  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 34 0a  |SECTOR=00000004.|
    00000a00  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 35 0a  |SECTOR=00000005.|
    00000c00  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 36 0a  |SECTOR=00000006.|
    00000e00  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 37 0a  |SECTOR=00000007.|
    00001000  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 38 0a  |SECTOR=00000008.|
    00001200  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 39 0a  |SECTOR=00000009.|

    # hexdump -C /dev/sdb2 | fgrep -v '*' | tail -3
    1efffc00  53 45 43 54 4f 52 3d 30  31 30 31 35 38 30 36 0a  |SECTOR=01015806.|
    1efffe00  53 45 43 54 4f 52 3d 30  31 30 31 35 38 30 37 0a  |SECTOR=01015807.|
    1f000000

Use GParted to copy unrecognised content from the partition to the
encrypted Logical Volume.  The copy reports success.
    * Copy /dev/sdb2 to /dev/testvg/lvol1                      (SUCCESS)
      * calibrate /dev/sdb2                                    (SUCCESS)
          path: /dev/sdb2 (partition)
          start: 2099200
          end: 3115007
          size: 1015808 (496.00 MiB)
      * calibrate /dev/testvg/lvol1                            (SUCCESS)
          path: /dev/testvg/lvol1 (logical volume)
          size: 128 (512.00 MiB)
          encrypted path: /dev/mapper/lvol1_crypt
      * clear old file system signatures in /dev/mapper/lvol...(SUCCESS)
      * copy file system from /dev/sdb2 to /dev/mapper/lvol1...(SUCCESS)
          using internal algorithm
          copy 496.00 MiB
        * finding optimal block size
        * copy 416.00 MiB using a block size of 8.00 MiB       (SUCCESS)
          496.00 MiB (520093696 B) copied
      * check file system on /dev/sdb2 for errors and (if po...(WARNING)
          checking is not available for this file system

Data after copying is different to the source.  From sector 4 onwards it
is from the wrong place.
    # hexdump -C /dev/mapper/lvol1_crypt | fgrep -v '*' | head
    00000000  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 30 0a  |SECTOR=00000000.|
    00000200  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 31 0a  |SECTOR=00000001.|
    00000400  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 32 0a  |SECTOR=00000002.|
    00000600  53 45 43 54 4f 52 3d 30  30 30 30 30 30 30 33 0a  |SECTOR=00000003.|
    00000800  53 45 43 54 4f 52 3d 30  30 30 33 32 37 36 38 0a  |SECTOR=00032768.|
    00000a00  53 45 43 54 4f 52 3d 30  30 30 33 32 37 36 39 0a  |SECTOR=00032769.|
    00000c00  53 45 43 54 4f 52 3d 30  30 30 33 32 37 37 30 0a  |SECTOR=00032770.|
    00000e00  53 45 43 54 4f 52 3d 30  30 30 33 32 37 37 31 0a  |SECTOR=00032771.|
    00001000  53 45 43 54 4f 52 3d 30  30 30 36 35 35 33 36 0a  |SECTOR=00065536.|
    00001200  53 45 43 54 4f 52 3d 30  30 30 36 35 35 33 37 0a  |SECTOR=00065537.|

    # hexdump -C /dev/mapper/lvol1_crypt | fgrep -v '*' | tail -3
    1a002600  53 45 43 54 4f 52 3d 30  31 30 31 35 38 30 37 0a  |SECTOR=01015807.|
    1a002800  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
    1f000000

GParted_Core::copy_blocks() copies the first 80 MiB in 5, 16 MiB chunks
with block sizes of 1, 2, 4, 8 and 16 MiB as a benchmark to determine
the optimal block size.  It then copies the remainder using the optimal
block size.  copy_blocks() calculates what to copy in source and
destination sector size units.  It calls the CopyBlocks class to copy
the chunk passing offsets into the source and destination in sector size
units.  CopyBlocks class gets the actual source and destination sector
sizes and works in those offsets.  When copy_blocks() and CopyBlocks
class are using the same sector sizes everything works.

Graphically it looks like this:

    [ 1M BS][ 2M BS][ 4M BS][ 8M BS][16M BS][optimal BS for remainder]
      copy ... ->
        |
        v
    [ 1M BS][ 2M BS][ 4M BS][ 8M BS][16M BS][optimal BS for remainder]

    Legend:
    BS     - Block Size
    ... -> - Direction of reading source
    []     - Copy chunk boundary
    |
    v      - Copy destination

However in test 2, copying from the disk partition into an encrypted
Logical Volume copy_blocks() was informed the destination sector size
was 4 MiB, but the actual sector size was only 512 bytes.  Therefore
copy_blocks() advanced the destination write offset by 4 sectors (16 MiB
benchmark copy chunk size divided by 4 MiB sector size), but CopyBlocks
class interpreted that as 4, 512-byte sectors.  The result was that each
chunk overwrote the previous chunk with an offset of 4 sectors.

Graphically it was doing this:

    [ 1M BS][ 2M BS][ 4M BS][ 8M BS][16M BS][optimal BS for remainder]
      copy ... ->
        |
        v
    [ 1M BS]
     [ 2M BS]
      [ 4M BS]
       [ 8M BS]
        [16M BS]
         [optimal BS for remainder]__________not_overwritten__________

There is an extra complication with the copy algorithm that when the
destination offset is larger than the source offset the copy works
backwards from the end to the beginning so that is can safely copy data
for an in-place partition move.

Graphically it looks like this:
(not representing the different source and destination partition
offsets)

    [optimal BS for remainder][16M BS][ 8M BS][ 4M BS][ 2M BS][ 1M BS]
                                                         <- ... copy
                                                                  |
                                                                  v
    [optimal BS for remainder][16M BS][ 8M BS][ 4M BS][ 2M BS][ 1M BS]

In test 1, copying from an encrypted Logical Volume to a disk partition
copy_blocks() was informed the source sector size was 4 MiB, but the
actual sector size was only 512 bytes.  Therefore copy_blocks() was
passing a source read sector offset that was 8192 times too small
(4 MiB / 512) for each of the 5, 16 MiB benchmarking chunk copies that
were meant to be from the end of the source data.  The wrong data was
read, however it was written to the intended destination.  The remainder
chunk copy using the optimal block size was correctly copied from the
start of the source to the start of the destination.  The result was the
start of the copied was correct with just the final 80 MiB containing 5
chunks of 16 MiB copied from the wrong place.

Graphically it was doing this:

                [ 1M BS]
               [ 2M BS]
              [ 4M BS]
             [ 8M BS]
            [16M BS]
    [optimal BS for remainder]_______________not_copied_______________
           <- ... copy
                    |
                    v
    [optimal BS for remainder][16M BS][ 8M BS][ 4M BS][ 2M BS][ 1M BS]

A VGDevice's sector_size is set to the Volume Group's PE (Physical
Extent) size, 4 MiB by default.  This is passed on to the Partition's
sector_size representing the Logical Volume and then on to the
Partition's sector_size representing the open encryption mapping in the
Logical Volume.

Copying of a partition opens the whole disk device and uses its offset
and length to define the partition.  Copying of a whole disk device,
open encryption mapping and a Logical Volume all copy using it's own
/dev entry and from offset zero.  Fix this corrupting copy by making
get_copy_target() treat whole disk devices and open encryption mappings
(both TYPE_UNPARTITIONED) the same as Logical Volumes to query the
actual sector_size.

[1] write-sector-pattern.py

"""write-sector-pattern.py - Write a verifyable unique data pattern to
every sector of a block device

Every sector is filled with this data pattern and the sector number is
set appropriately:
    SECTOR=00000000
    SECTOR=00000000
    ...
This allows easy verification that each sector has been copied correctly
and to the correct location.

Command line usage:
    write-sector-pattern.py [DEVICE]
"""

import argparse
import array
import errno
import fcntl
import os
import sys

BLKSSZGET = 0x1268
DEFAULT_SECTOR_SIZE = 512
PATTERN_SIZE = 16

def get_sector_size(fd):
    """Return sector size for the open fd (file descriptor) on a device.
    Uses ioctl(fd, BLKSSZGET) to report the logical sector size of the
    device.  On ioctl() failure return default of 512.
    """
    sector_size = 0

    buf = array.array('i', [0])
    try:
        fcntl.ioctl(fd, BLKSSZGET, buf, True)
        sector_size = buf[0]
    except OSError as e:
        print(f"WARNING: {e}")

    if sector_size == 0:
        print(f"INFO: Using default sector size {DEFAULT_SECTOR_SIZE}")
        return DEFAULT_SECTOR_SIZE

    print(f"INFO: Sector size {sector_size}")
    return sector_size

def write_sector_pattern(name):
    """Write a verifyable unique data pattern to every sector of the
    named device.

    Every sector is filled with this data pattern and the sector number
    is set appropriately:
        SECTOR=00000000
        SECTOR=00000000
        ...
    """
    try:
        fd = os.open(name, os.O_WRONLY|os.O_CREAT)
    except OSError as e:
        print(f"ERROR: '{name}': {e}", file=sys.stderr)
        sys.exit(1)

    sector_size = get_sector_size(fd)
    repetitions = sector_size // PATTERN_SIZE
    fragment    = sector_size % PATTERN_SIZE
    sector_num  = 0
    while True:
        # Prepare sector sized identifiable data pattern with the sector
        # number being set appropriately:
        #     SECTOR=00000000
        #     SECTOR=00000000
        #     ...
        pattern = f"SECTOR={sector_num:08d}\n".encode('ascii')
        sector_buffer = pattern * repetitions + pattern[:fragment]

        # Write sector data pattern.
        try:
            bytes_written = os.write(fd, sector_buffer)
            if bytes_written != sector_size:
                raise OSError(f"os.write(): Short write.  Attempted {sector_size}, wrote {bytes_written}")
        except OSError as e:
            if e.errno == errno.ENOSPC:
                print (f"INFO: Wrote {sector_num} sectors")
                break
            else:
                print(f"ERROR: '{name}': {e}", file=sys.stderr)
                sys.exit(1)

        sector_num += 1

    os.close(fd)

def main(args=None):
    """Parse command line arguments and call sector writing function"""
    parser = argparse.ArgumentParser(description="""
        Write a verifyable unique data pattern to every sector on a
        block device.""")
    parser.add_argument("device",
        help="Device or file name to write sector data pattern to")
    args = parser.parse_args(args)
    write_sector_pattern(args.device)

if __name__ == '__main__':
    sys.exit(main())

Closes #328 - Support file system manipulation operations not requiring
              LVM changes